layout_spectrum: 0.6554473
typography_spectrum: 0.3172043
color:
  saturation: 0.8405018
  brandStrength: 0.833981
  lightness: 0.516129
  rhythmicContrast: 0.7849463
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: kuma no yukue
