collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.3172043
color:
  saturation: 0.8405018
  brandStrength: 0.833981
  lightness: 0.7222222
  rhythmicContrast: 1
layout_spectrum: 0.6290323
name: kuma no yukue
